Do not assume a specific order of headers
nachomazzara/parse-multipart-data pull request #9
Opened 2022-05-31 11:46 UTC by simhnna

The spec doesn't appear to define an order. I receive the headers in different order.

I needed to comment the code to work out how it works. After I've done that I refactored it a little so it hopefully is a little easier to read

2022-05-31 11:54 UTC, simhnna commented
Here's the part of the RFC that says the order isn't relevant https://datatracker.ietf.org/doc/html/rfc2045#section-3

2022-05-31 15:31 UTC, nachomazzara requested changes
Hey! Thanks for the contribution. 

I've requested some formatting changes.

2022-05-31 15:31 UTC, nachomazzara commented on src/multipart.ts
> +    boundary: '----WebKitFormBoundaryvef1fLxmoUdYZWXp',
Can we remove the trailing comma?

2022-05-31 15:31 UTC, nachomazzara commented on src/multipart.ts
> +      configurable: true,
can we remove the trailing coma?

2022-05-31 15:31 UTC, nachomazzara commented on src/multipart.ts
> +      configurable: true,
can we remove the trailing coma?

2022-05-31 15:31 UTC, nachomazzara commented on src/multipart.ts
> +      configurable: true,
can we remove the trailing coma?

2022-05-31 15:31 UTC, nachomazzara commented on src/multipart.ts
> +    configurable: true,
can we remove the trailing coma?

2022-06-01 20:13 UTC, simhnna commented
> Hey! Thanks for the contribution.
> 
> I've requested some formatting changes.

I ran prettier after my changes since I saw config for it in the package.json 
Maybe the config needs to be updated? I can manually remove the commas

2022-07-15 04:56 UTC, crtag commented
Such a good PR held by a comma which is a good practice to have in where it is now? The package is practically useless without this change.

2022-08-16 12:38 UTC, nachomazzara commented
@simhnna the package lock maybe out of date. Can you send a resolve the conflicts so I can merge the PR?

2022-08-16 15:03 UTC, simhnna commented
Sorry. had other work to do and then was on parental leave. Conflict resolved, commas removed and I updated the prettier config so it doesn't add the commas back

2022-08-16 15:21 UTC, merged

2022-09-15 11:27 UTC, nachomazzara commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/parse-multipart-data/v/1.5.0)
- [GitHub release](https://github.com/nachomazzara/parse-multipart-data/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: